version: '2'
services:
  sdk_vs:
    container_name: tornado_project
    image: tornado_project
    #command: sh gunicornd.sh start -s
    #对应于docker run中的 -i ,第二个对应于 -t .
    stdin_open: true
    tty: true
    volumes:
      - .:/data/tornado_project
    ports:
      - "9010:9010"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"