sdk_vs:
  container_name: tornado_project
  image: xzregg/tornado_project
  command: sh gunicornd.sh start -s
  #对应于docker run中的 -i ,第二个对应于 -t .
  stdin_open: true
  tty: true
  volumes:
    - .:/data/tornado_project
  ports:
    - "8000:9010"
  restart: always
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "3"
  environment:
    MYSQL_ROOT_PASSWORD: redhat
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress